[package]
name = "substreams-uniswap-v3"
version = "0.1.0"
description = "Uniswap v3 Substreams"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ethabi = "17.0"
wasm-bindgen = "0.2.79"
prost = "0.11.0"
prost-types = "0.11.0"
hex = "0.4.3"
#substreams = "0.2.0"
substreams = { path = "../substreams-rs/substreams" }
#substreams-ethereum = { version = "0.5.0" }
substreams-ethereum = { path = "../substreams-ethereum/substreams-ethereum" }
num-bigint = "0.4"
bigdecimal = "0.3"
pad = "0.1"
base64 = "0.13.0"
stable-hash_legacy = { version = "0.3.3", package = "stable-hash" }
stable-hash = { version = "0.4.2"}
thiserror = "1.0.25"
num-traits = "0.2.15"

[build-dependencies]
prost-build = "0.11.0"
anyhow = "1"
#substreams-ethereum = { version = "0.5.0" }
substreams-ethereum = { path = "../substreams-ethereum/substreams-ethereum" }
